version: '3'

services:
  thredds-local:
    build: .
    ports:
      - "80:8080"
      - "443:8443"
      - "8443:8443"
    container_name: thredds
    volumes:
      - ../logs/tomcat:/usr/local/tomcat/logs/
      - ../logs/thredds:/usr/local/tomcat/content/thredds/logs/
      - ../config/tomcat-users.xml
      - ../content:/usr/local/tomcat/content/thredds
      - ../content/data:/data/
    env_file:
      - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"
    healthcheck:
          disable: false
    restart_policy:
      condition: on-failure